BEGIN;
SELECT plan(28);
SET ROLE anon;
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"shortenProductNames":false,"productNameMaxCharacters":40,"showSku":true}',NULL)$$,'42501',NULL,'anonymous cannot save shared defaults');
RESET ROLE;
SET ROLE authenticated;
SELECT throws_ok($$SELECT public.pos_admin_apply_shared_receipt_settings('org_a','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'42501',NULL,'authenticated cannot bulk apply layout');
RESET ROLE;
SET ROLE service_role;
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"shortenProductNames":false,"productNameMaxCharacters":40,"showSku":true,"presentation":{"templateVersion":1,"businessName":"Shared CETECH","address":"Shared address"}}',NULL)$$,'service role saves organization default');
SELECT is((SELECT count(*)::int FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id IS NULL),1,'one org default row');
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"shortenProductNames":false,"productNameMaxCharacters":40,"showSku":true}',NULL)$$,'updating org default uses same row');
SELECT is((SELECT count(*)::int FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id IS NULL),1,'NULL scope unique key prevents duplicates');
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings('org_a','loc_a1','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true,18,false,'{"templateVersion":1,"businessName":"Old branch","address":"Local address","contactPhone":"Local phone","taxRegistrationNumber":"Local tax","footerMessage":"Local footer"}')$$,'legacy settings preserved until explicit apply');
SELECT ok((SELECT settings_override IS NULL FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'legacy row remains full override');
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a','loc_a2','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',NULL,'{"showSku":false,"presentation":{"address":"","showCashier":false,"logoDataUrl":null}}')$$,'sparse explicit false blank null logo allowed');
SELECT is((SELECT settings_override FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a2'),' {"showSku":false,"presentation":{"address":"","showCashier":false,"logoDataUrl":null}}'::jsonb,'sparse values survive storage');
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a','loc_a1','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',NULL,'{"extra":true}')$$,'23514',NULL,'unknown override field rejected');
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a','loc_a1','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',NULL,'{"presentation":{"logoDataUrl":"https://example.test/logo"}}')$$,'23514',NULL,'external logo rejected');
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a','loc_b1','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',NULL,'{}')$$,'23503',NULL,'cross organization override rejected');
SELECT is((SELECT presentation->>'businessName' FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'Old branch','saving shared defaults did not change legacy branding');
SELECT lives_ok($$SELECT public.pos_admin_apply_shared_receipt_settings('org_a','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'one explicit bulk action applies common layout');
SELECT is((SELECT settings_override FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'{"presentation":{"address":"Local address","contactPhone":"Local phone","taxRegistrationNumber":"Local tax"}}'::jsonb,'bulk retains local details only');
SELECT is((SELECT settings_override FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a2'),'{"presentation":{"address":""}}'::jsonb,'bulk keeps explicit blank local address and clears common flags and logo');
SELECT is((SELECT count(*)::int FROM public.pos_receipt_settings WHERE organization_id='org_b'),0,'bulk never touches other organization');
SELECT is((SELECT count(*)::int FROM public.pos_admin_audit_events WHERE organization_id='org_a' AND action='receipt_settings.inherit_layout'),2,'bulk creates audit at each scoped location');
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"shortenProductNames":false,"productNameMaxCharacters":40,"showSku":true,"presentation":{"templateVersion":1,"logoDataUrl":"data:image/png;base64,iVBORw0KGgo="}}',NULL)$$,'shared logo is saved before old SKU-only caller');
SELECT lives_ok($$SELECT public.pos_admin_set_receipt_settings('org_a','loc_a1','owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',false,24,true)$$,'legacy full save still works after sparse override');
SELECT is((SELECT settings_override->'presentation' FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'{"address":"Local address","contactPhone":"Local phone","taxRegistrationNumber":"Local tax"}'::jsonb,'old SKU-only caller preserves sparse local details');
SELECT is((SELECT settings_override->>'showSku' FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'true','old SKU-only caller writes scalar overrides');
SELECT is((SELECT presentation->>'logoDataUrl' FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id IS NULL),'data:image/png;base64,iVBORw0KGgo=','old SKU-only caller leaves inherited logo intact');
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"shortenProductNames":false,"productNameMaxCharacters":0,"showSku":true}',NULL)$$,'23514',NULL,'shared invalid max rejected');
SELECT throws_ok($$SELECT public.pos_admin_set_receipt_settings_scope('org_a',NULL,'owner_a','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',NULL,'{}')$$,'23514',NULL,'organization scope requires full settings');
RESET ROLE;
CREATE FUNCTION public.pos_test_fail_shared_receipt_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='receipt_settings.inherit_layout' AND NEW.location_id='loc_a2' THEN RAISE EXCEPTION 'audit failure' USING ERRCODE='P0001'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER pos_test_fail_shared_receipt_audit BEFORE INSERT ON public.pos_admin_audit_events FOR EACH ROW EXECUTE FUNCTION public.pos_test_fail_shared_receipt_audit();
SET ROLE service_role;
SELECT throws_ok($$SELECT public.pos_admin_apply_shared_receipt_settings('org_a','owner_a','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')$$,'P0001',NULL,'failure at second audit aborts entire bulk operation');
SELECT is((SELECT settings_override->>'showSku' FROM public.pos_receipt_settings WHERE organization_id='org_a' AND location_id='loc_a1'),'true','first location scalar override unchanged after later audit failure');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
