"""Deterministic schema-to-TS declarations for this repository's schema subset."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def ts(x):
    if '$ref' in x:return x['$ref'].split('/')[-1]
    if 'const' in x:return json.dumps(x['const'])
    if 'enum' in x:return ' | '.join(json.dumps(v) for v in x['enum'])
    if 'oneOf' in x:return ' | '.join('('+ts(v)+')' for v in x['oneOf'])
    t=x.get('type')
    if t=='object':
        fields=['readonly '+k+('' if k in x.get('required',[]) else '?')+': '+ts(v)+';' for k,v in x['properties'].items()]
        return '{ '+ ' '.join(fields)+' }'
    if t=='array':return 'ReadonlyArray<'+ts(x['items'])+'>'
    if t in ['number','integer']:return 'number'
    if t in ['string','boolean','null']:return t
    raise ValueError('Unsupported schema construct: '+str(x))
def generate():
    d=json.loads((ROOT/'docs/contracts/pos-domain.schema.json').read_text())['$defs']
    return '// GENERATED by scripts/generate_contract_types.py. Do not edit.\n// JSON Schema is authoritative; TS declarations do not replace runtime validation.\n\n'+'\n'.join('export type '+k+' = '+ts(v)+';' for k,v in d.items())+'\n'
if __name__=='__main__':
    out=ROOT/'docs/contracts/domain.generated.ts'; content=generate()
    if '--check' in sys.argv:
        if not out.exists() or out.read_text()!=content: raise SystemExit('Generated contracts drift; run python3 scripts/generate_contract_types.py')
        print('Generated TypeScript matches schema')
    else:out.write_text(content)
